language: ruby
rvm:
- 2.2.4
before_install: gem update --remote bundler
services:
- postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: U0qhfzYO/B424xflTZBiEVjk72BGXoowAGmWtjMAzN3YwDXp+PkpkEBPpEQUTLGgzqRsWVM65FYIBaiB9sZ9bE8JuAxSOW71RMwCzPctm5xC6GhG0ZNijqMxamuQDPSId7oLVmOLNTk9jWqWH20yIewbkGWWfcTMJ0NksF3fYtJHaR00rIpUsWTEkyftEW8fWGPXoeDw357w+9KdNvrUfeIyT4vkIu9sGtCBo0YcVTLETl9p8op/gTJabVuLzsnYMFbmBMYeZYv0jvZgn9W3RP6/ZKdX/Xo7LV6v6dv4/1HXq2aZFXDdr3kzQuXMH3qvByr3ZHfMBFrbEuLHMx9qRb9MpVviTZiy8UcyKSMbxrShvFZEvCDJOXqgxQiaUck9I+o+BW872eA/+OUj9QdVYbioELy32n2zohq8lwiz5ucEP6oTmxHwx9O+dG1rvOqxZoQdhu0cr4XpszhAFl2dj7gSK/yMlBqGCo5XGsmuAFQrty9IfAPkua7mEs4ucMs0/WzRPbRIjyTg1VPbQXPVlhf6EJaYbLvxrrppSPVpPHD9yYld4hjAJx3iG9t+M13rl5D1D7/N0sQLJ8YHSMoiPX6mZtZhqdpXN3FeNarjO8L+czG2q2RpshD6jd7NC731Qs/bFR7dPeg4RXnpfDfsnkps0E/h6FazJyGyKhqcDwY=
  app:
    master: orionchess
  on:
    repo: FirehoseProjectTeamOrion/OrionChess
addons:
  code_climate:
    repo_token: #Token Goes Here