language: ruby
rvm: 
- "2.2.4"
before_install: 
- gem update --system
- gem --version
install: 
- bundle install --retry=3
script:
- bundle exec rspec
- bundle exec rubocop
# deploy:
# 	provider: heroku
# 	api_key:
# 		secure: 3866da66-5234-4928-b7ee-9a2a917df063
